### ISSUE TITLE
Support for `overrideModuleCreation`

### ISSUE THREAD

**Issue by kwickramasekara** [Kamiapp-fr/vite-plugin-cem#8]
Hello, thank you for this great plugin. I was trying to use [expanded types](https://github.com/break-stuff/cem-tools/tree/main/packages/expanded-types) plugin with CEM and it requires that you set `overrideModuleCreation` as shown in CEM [docs](https://custom-elements-manifest.open-wc.org/analyzer/plugins/authoring/#overriding-sourcefile-creation). 

It looks like the expanded types plugin does not work when used with Vite and throws the following error:

```
[expand-types-plugin]: Looks like you've hit an error in third party plugin: expand-types-plugin. Please try to create a minimal reproduction and inform the author of the expand-types-plugin plugin.
 TypeError: Cannot read properties of undefined (reading 'getDeclaredTypeOfSymbol')
 ```
 
 Do we know if `overrideModuleCreation` can be set similar to `custom-elements-manifest.config.mjs`?

**Comment by EmilienLeroy** [comment]
Hi @kwickramasekara 
Thank you for your interest in this plugin. Could you please provide a repository that reproduces the error? I have limited time available for this project, but I'll do my best to take a look at your issue.

**Comment by gambolputty** [comment]
Hey @kwickramasekara, thanks for creating this plugin!

I need to set the `overrideModuleCreation` option as well. In the [readme of this vite plugin](README.md) we can see all config options that are passed to [@custom-elements-manifest/analyzer](https://github.com/open-wc/custom-elements-manifest/tree/master/packages/analyzer) as far as I can see. But `overrideModuleCreation` is missing. It's [a config option](https://custom-elements-manifest.open-wc.org/analyzer/config/#config-file) for the analyzer plugin.

I think the author of this issue is asking if you could make passing this option as well in the `CreateManifestOptions `.

**Comment by EmilienLeroy** [comment]
Hi @gambolputty 
Thank you for your explanation, it has provided me with a clearer understanding of the issue. 
I will implement the suggested option this week, if time allows. Alternatively, if you would like to contribute, feel free to submit pull requests, they would be greatly appreciated.

**Comment by EmilienLeroy** [comment]
Hi @kwickramasekara  and @gambolputty 

I have just released a [new version](https://github.com/Kamiapp-fr/vite-plugin-cem/releases/tag/v0.7.0) that includes the `overrideModuleCreation` option in the plugin. 
Additionally, I've provided an [example](https://github.com/Kamiapp-fr/vite-plugin-cem/blob/main/example/lit-expanded-types/vite.config.js) illustrating how to use it.
Can you give it a try and inform me if it fulfills your requirements.

**Comment by kwickramasekara** [comment]
Amazing - works like a charm! Thank you so much for your efforts @EmilienLeroy! Closing the issue as resolved!
